---
title: "Larynx cancer in Germany: solution"
output:
  html_document:
    number_sections: yes
    toc: yes
  pdf_document:
    toc: yes
---

<!--
%\VignetteEngine{rmarkdown::render}
%\VignetteIndexEntry{qgam_vignette}
-->
  
```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(out.extra='style="display:block; margin: auto"', fig.align="center", tidy=FALSE)
```

```{r setup1, include=FALSE}
# Set workdir to source file location and then
source(file = "my_settings.R")
library(RhpcBLASctl); blas_set_num_threads(1)
```

1) Load data and fit a Poisson GAM with MRF smooth:
```{r lary1, message = F}
library(mgcViz)
load(paste0(goodLocation, "/data/Larynx.rda")) # change this
load(paste0(goodLocation, "/data/german.polys.rda")) # change this

X <- t(sapply(german.polys,colMeans,na.rm=TRUE))

fit1 <- gamV(Y ~ s(region, k = 200, bs="mrf",xt=list(polys=german.polys)) + offset(log(E)) + s(x, k=20),
             family=poisson, data=Larynx, aViz = list(nsim = 50))

print(plot(fit1), ask = FALSE)
```

2) Now use isotropic TPS smooth:
```{r lary2, message = F}
fit2 <- gamV(Y~s(X[,1],X[,2],k=200)+offset(log(E))+s(x,k=20), family=poisson, data=Larynx)

print(plot(fit2, select = 1), ask = FALSE)
```

Now use tensor-product smooth:
```{r lary3, message = F}
fit3 <- gamV(Y~te(X[,1],X[,2],k=c(15, 15))+offset(log(E))+s(x,k=20), family=poisson, data=Larynx)

print(plot(fit3, select = 1), ask = FALSE)

AIC(fit1, fit2, fit3)
```
MRF model is better in terms of AIC.

3) Now visualize effect using rgl:
```{r lary4, message = F}
open3d()
mfrow3d(1, 2)
plotRGL(sm(fit2,1), residuals = TRUE)
next3d()
plotRGL(sm(fit3,1), residuals = TRUE)
rgl.close()
```
Tensor effect seems smoother.
